name: TFLint
on:
  push:
    branches: main
    paths:
      - '**.tf'
  workflow_dispatch:
env:
  TF_DIR: 'src'
jobs:
  Linting:
    uses: froggologies/gcp-terraform-master-project/.github/workflows/tflint.yml